= 《程序员的认知心得》电子书

== 写作说明

我有幸在一家非常有趣的公司工作，这家公司的同事都很爱思考，我从中学习到很多新颖的观点和深刻的洞见。

这些见解从另外的角度看待软件开发的过程、逻辑、方法论以及团队，这些内容让我收获甚多。

工作之余，把和同事们交流的过程中的心得写成了博客发表在微信公众号吸引了一些感兴趣的小伙伴。

这本电子书将这些博客和交流所得整理出来，让它初具结构和逻辑并分享出来。

有缘看到这本电子书并产生兴趣的朋友可以一起交流，希望获得您宝贵的意见。

HTML 版本访问地址：https://linksgo2011.github.io/a-programmer-s-cognitive-experience/

PDF 下载地址：https://github.com/linksgo2011/a-programmer-s-cognitive-experience/releases/tag/v1.0.0

== 电子书构建指南

这本电子书最初使用 Markdown 构建，但是后来发现 Asciidoctor 相比 Markdown 更适合多章节的内容结构，因此切换为 Asciidoctor 构建。

参考本项目，你也可以构建出自己的电子书（HTML、PDF），参考命令如下。

=== Mac 原生命令

Mac 安装 Asciidoctor：

 $ brew install asciidoctor

生成 HTML：

 $ asciidoctor -vwt -o output/a-programmer-s-cognitive-experience.html index.adoc

生成 PDF：

 $ asciidoctor-pdf -a pdf-theme=./themes/cjk-theme.yml -a pdf-fontsdir="./themes;GEM_FONTS_DIR" -a scripts=cjk -o output/a-programmer-s-cognitive-experience.pdf index.adoc

=== Docker 容器命令

Docker 安装

 $ docker pull asciidoctor/docker-asciidoctor

启动命令

 $ docker run -it --rm -v $PWD:/documents asciidoctor/docker-asciidoctor

运行命令和本地一致。

=== 参考资料

- https://docs.asciidoctor.org
- Asciidoctor PDF Theming Guide for CJK issue https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.0.beta.7/docs/theming-guide.adoc#custom-fonts
- https://github.com/akosma/eBook-Template
