
=== 8.12 总结：政治的真相

政治是说谎的艺术。

真正的政治是暴力和欺骗的艺术，当然在职业环境中，大多数情况下暴力可以替换为职权力，而获取权力的过程也充满了欺骗和伪装。

正是因为政治背后具有欺骗和各种手段，这正是让人们羞于启齿的原因。但是这些欺骗无时不刻出现在生活和工作场合中，甚至让人们产生羞耻也是欺骗的一部分。

这些欺骗是为了更好的实现具体的政治手段，从而建立需要的秩序。这种欺骗从人类奴隶时代就开始了，甚至在人类文明出现之前就开始了。

蜥蜴和章鱼通过调整自身的颜色来伪装自己，从而躲过天敌和捕获猎物；某些蛾类通过伪装翅膀为枯叶和环境融为一起，这些都可以算作欺骗。

原始部落的首领和萨满通过假装和神灵沟通，从而欺骗部落成员，取得统治地位；封建君主欺骗民众，自诩为天子，虚构一套神话体系，让人觉得自己天生优越；西方教皇虚构了上帝，通过宗教进行欺骗。

在普世价值观下，欺骗是全方位的。中国古代儒家教育体系将虚假的价值观从小就植入到普通人的意识中。人性本善，是一种欺骗，掩盖人性自私的原本面目；将君子包装成大公无私的形象，实际上是获取私利的方法；宣传的人人平等也是一种欺骗，客观上个体之间永远不可能平等，贵族阶层一定会比普通人获得更多的资源。

甚至羞耻也是一种谎言。想想一种场景，在古代的丛林中，有一个部落。这个部落有一天打猎获取到了一只肥美的麋鹿，部落的人自然都想分享到麋鹿的美味。为了相对公平，部落首领在没有想好如何分配的情况下，先将麋鹿保存在部落公共的房子里。那么，每一个靠近屋子想打麋鹿主意的人，都会面临其他人的指责。羞愧，其实就是来源于众人的指责，有时候这里的"众人"甚至来自于父母或者家人。

想象上面的场景，如果将麋鹿换成部落中最漂亮的女性会发生什么？每一个靠近漂亮女性的男性都会来自其他男性的攻击、指责，这就是性羞耻的起源。

政治的无耻就在于这里，普世价值的真、善、美只是让对方相信，从而轻易卸下对方的武装。从某种程度上来说，人类发达的大脑不仅能在捕猎的时候做出完美的假动作实现智力对体力的降维打击，也能在人类内部竞争中充分发挥作用。

如果不能理解谎言在政治中的作用，那么从生活中可以随时观察他人，从他说话的动机出发，尝试理解话语背后的动机和目的。

说谎已经被刻画到人类的本性中，普世价值却鼓励别人诚实一点。如果大家都是诚实的，那么女性还需要化妆打扮、男性还需要好面子吗？我们有一天也快忘记，面子的本质也是欺骗——通过穿戴或其他物品伪装自己的经济水平而已。