== 第 8 章 软件工程中的政治

为什么我们不坦诚地聊聊工作中的政治？

按理说软件工程师是一个技术工种，学习政治会显得奇怪。在 Neal Ford 的《软件架构》中提到了架构师应该学习政治，并且他也觉得提到政治非常奇怪。

但是了解和驾驭政治几乎是架构师的必修课，因为架构师做出的每一个技术决策都可能受到挑战，因为没有决策会是完美并满足所有人诉求的。

架构师必须学会说服相关的利益方。比如说，一个古老的系统不得不进行重构，但是项目经理、产品经理可能完全不能理解为什么不能持续添加功能而停下来进行重构。有些情况下，技术决策会伤害某些人的利益。在这种情况下，理解政治才能游刃有余。

政治是与人相处并达成目标的艺术，虽然被用到技术行业听起来不道德，但是我们却无时无刻在使用这些技巧，只是从未将其成为“政治学”。

人类社会的竞争主要是智力竞争，暴力竞争并不是主要的竞争。政治并不是仅仅包含国家之间的竞争，而是包含任何单位之间的竞争，个体之间、公司之间、团队之间的竞争都可以用政治的相关理论和认知模型描述。

就像我们前面说的那样，技术问题背后往往是利益问题，而利益问题背后往往是政治问题。无论我们多么瞧不起那些玩弄政治的人，但总是得面对他们、了解他们、学习他们。

这一章主要讨论在工作中发现的一些关乎利益、政治这些"不堪"的现象。

=== "不堪" 但是有效的政治

据我所知，有一家做制造的传统公司为了推进数字化转型，为制造、采购等单位开发软件。按照测算，软件上线后可以裁员 40%，并节省大量开支。

但是 IT 部门却发现了一个问题，在需求分析阶段业务部门就非常不配合，并且勉强上线的产品也无法推广。原因是电子化后，一方面监管变得容易，没有灰色操作；另外一方面由于软件的替代作用，业务团队人员数量会被缩减，业务基层领导也不愿意看到这种情况，于是暗中阻挠希望维持团队规模。

IT 部门领导获得公司高层授意后，制定了一条政策：设立一项考试，获得电子化操作证书的员工优先提拔并重新评职级，这条政策本质是 IT 部门制定，却需要由业务部门执行。 这条政策的执行很快让软件的实际使用情况获得迅速提高。

在数字化推进的过程中，这个案例并不鲜见，我们来分析这个案例。

首先，在不使用政治手段时，IT 部门几乎没有办法提高软件使用率，如果把解决问题的方向放在软件体验上，将毫无用处（这条政策也有一个前提，软件的使用即使有一些问题，至少不耽误正常业务运转）。IT 部门使用了"不堪"政治手段，"不堪"的地方在两点。

1. 电子化是公司利益方向，是大势所趋，站在了名义高地，才能发布如此政策。
2. 考试的本质是隐晦地解除了基层领导的权利，争取一线员工的支持。
3. 使用一线员工竞争基层领导的策略，原本一线员工是潜在裁员对象，其实和公司处于矛盾状态，通过考试筛选的政策，拉拢大部分一线员工，迫使基层领导进行数字化转型。

这是一个"不堪"的政治示例，讲述了一个简单的道理：政治就是让朋友多多的，让敌人少少的。政治是操作矛盾的艺术，操纵民族矛盾对立，就可以消除阶级矛盾，而制造外部矛盾就可以缓解内部矛盾。

拉一个打一个是操纵矛盾的基本手法。

=== 管理咨询的秘密

拉一个打一个是普通手法，在软件行业中，甚至当没有人可以拉时，可以"买一个"，这就是接下来需要讲的故事。

可能有非常多的人和我一样不了解管理咨询公司到底做什么的，在社会中扮演者什么样的角色。我曾经一度对各大管理咨询公司的神秘抱有敬畏之心，直到后来才发现他们的秘密。

而这些秘密需要新的认知才能理解。

如今的管理咨询公司有点像古代的谋士或者门客。他们不是用高大上的方法论、专业的数据收集和调研来解决一些具体的问题，这些工作是研究院做的事情，这是一个普遍的误解。

我们换个角度思考，企业为什么需要管理咨询工作，甚至为它付高额的报酬？难道仅仅是因为管理咨询公司对某些领域更专业？请了咨询师不是打当前管理者的脸嘛？

本质原因是一些难以推动的事情需要通过管理咨询公司的包装才能进行下去。如果一个公司需要对组织结构进行调整，那么直接动手会遇到极大的阻力。很简单的方法，包装一个高大上的项目和计划，例如进行变革、创新等行动，在行动中顺理成章的实现超出管理能力范围内的目标。

咨询师如果真的给出了"专业"的建议并否定了当前管理者的管理政策，那么必然会碰一鼻子灰。而真正的认知是，读懂并理解当前管理者的意图，并积极给予帮助。

=== 权利的来源

从管理咨询的作用是达成雇主目标的工具这条认知出发，我们需要思考一个问题：权利的来源有哪些？

如果管理者有绝对的权利，下面的人对其言听计用，那么花钱购买咨询服务自然就没有必要了。从某种程度上来看，购买而来的咨询服务就成了行使权利的手段。

和我们常常理解的不同的是，名义上的领导往往无法行使与其表面相称的权利，而是被四处掣肘。

对于公司来说权利的最终来源是人事权、经济权。所以一般情况下，权利的来源是具有人事权的领导授予的，而不是来自团队成员的支持。"悦上者荣,悦下者蹇" 说的就是这个逻辑，取悦领导的人往往混的比较好，而争取得到下属支持的人却不受优待，这是因为权利来源客观决定的。

虽然权利的来源不是下属，执行任务时需要得到下属支持，这点容易让人混淆权利的来源。所以实际上的领导争取下属的支持，但是权利的基础却不在这里。某些人拉拢同事对抗领导，相当于平白无故的争取权利，是没有人能接受的。

在写这条认知的时候感到非常残酷，却越想越是如此。我们能在历史中找到非常多类似的示例，在工作中也能发现不少蛛丝马迹。 当然权利的来源不仅仅如此，否则所谓的"政治"就太简单了，权利的另外来源还有能控制的资源。

对于销售为核心的公司，客户资源往往是隐性权利的来源；而对于技术为核心的公司来说，核心技术掌握也是权利的来源；群众的支持也算一种权利的来源，不过微不足道。

这些隐性的权利来源往往会和官方权利来源出现矛盾，这就是"政治"游戏的中心了。从各方的动机上来说，领导者的职责就是不断拆解隐性权利的影响，平衡团队。而隐性权利的受益人来说，自然不肯放弃，这就形成了极其复杂的博弈。

权利另一种的来源更加"不堪"，那就是伤害别人和造成破坏的能力。在社会中这类的例子非常多，不过过于敏感暂且不说。即使在软件工程行业，通过"掀桌子"获取权利的案例也比比皆是。最不堪的就是恶化代码质量，人为地提高自己的门槛也不失为一个例子。

除此之外，抢占道义的高地也是获取权利的方式之一，这也是一些公司部门为什么抢着申报"创新"、"变革"等项目，利用这些项目可以对权利体系造成道义影响，行使超出自己职权范围外的权利，俗称"拉虎皮扯大旗"。

=== 规则和秩序

通过权利来源的分析，我们会发现一个非常有意思的现象。现实生活中，很多事情并不像表面运行的那样，而是通过一些隐性的东西在支配和运转。

我们可以把表面支配我们生活的东西叫做规则。这些规则可能是工作制度、道德、法律，但是更多的是运行在规则之下的规则。有一些人把这类东西叫做"潜规则"，而我可能更愿意叫做秩序。

规则是名义上的，而秩序却必然存在，而秩序就是通过权利体系构成的。

比如一个公司表面上由老板决定了如何分配工作和任务，一线的员工却把苦逼的事情额外的给了实习生，在老板无法事无巨细管理的地方由隐藏的秩序支配。

有时候会因为秩序的改变让事情走向截然不同的方向。举个狗血的例子来说，公司老板和经理的管理模式，构成了基本的秩序和权利格局。如果有一天，公司老板和市场部某位女性产生了不正当关系，原有的格局慢慢发生变化，新的秩序变形成了。

新来的员工在只知道明面上规则的情况下，不了解真实的秩序，那么极大可能在不该遇到麻烦的地方碰壁。

一个残酷的事实是，秩序的建立不受道德、公平和正义的丝毫影响。换句话说现实没有公平，只有秩序。

如果在一个学校的某班级中，按照规定应该平等的调整座位，如果班主任不进行干预，那么很快调整座位这件事就会变成秩序的体现，被霸凌的学生就只能永远坐最后一排。

另外一个更残酷的事实是，秩序只被有意愿且有能力影响局面的人影响，或者被某些事件影响。延续前面被霸凌的例子，如果被霸凌者去找老师投诉座位调整问题，如果遇到不负责的班主任老师，往往不会干预甚至觉得烦扰。如果被霸凌者接受了这个事实，那么不公平的秩序就建立了，除非通过某些极端手段改变当前的秩序。

关于秩序的问题，带入到软件公司和团队中并不会有太大差异。某公司一个团队负责人给自己的头衔是“架构师” ，然后请了一个外包项目经理催进度。听起来挺离谱的，但是这名"架构师"却是团队真正秩序的主导者，还不用做催进度的坏人，有时候甚至还可以和开发团队共情。

=== 分析利益和动机

在公司的环境下，盈利是商业公司的目的，那么秩序往往由利益这只看不见的手控制的。

所以很多看似愚蠢的事情也能理解了。对于能作为领导的人，你以为他很蠢，其实是坏；你以为是坏，但是其实还是为了挣钱。

而为了挣钱就是利益驱动，有的时候个体利益和群体利益毫不相干。把含铜的电线偷来卖掉，获得极少的个人利益，但是却损失了极大的群体利益，这种事情在大型企业中非常常见。

所以，道家的杨朱学派提倡秩序的建立者应当认识到这种自私的人性。形容普通人是"拔一毛以利天下而不为"的本性，热衷于奉献的人是为了在博弈中获得更大的利益，而不是当下的小利益。

利益和动机是了解软件团队中非常有利的方法。匹配其动机的事，不需要推动就会顺利，而不匹配其动机推起来就非常困难，而动机往往是和利益绑定的，即使推动某些事情会损害公司利益。

举个例子来说，推广单元测试这件事情从长期来看无论是对公司、团队领导、开发人员都是非常有益的，但是实际情况从很难推动。

因为没有人具有太多编写单元测试的动机。开发人员短期内会增加工作量，对于团队领导来说看不到快速的收益，无法纳入 KPI 管理。除非有追求的开发者，为了长期构建质量内建坚持推动外，不具备自发性推动的动机。

因此很多公司可以通过利益捆绑，在 KPI 中增加单元测试覆盖率的指标，进而制造编写单元测试的动机。

所以动机和利益给我们启示是：不要说服你觉得合适的人合作，而是筛选有动机的人合作，即使一个人图名，一个图利，甚至只是图个开心也需要有动机才能达成合作。

=== 形势：群体的动机

了解一个人的动机的威力就已经足够大了，那么如果是群体的动机呢？

这就是接下来需要讲的政治工具：形势。

如果一个人想创业的方向是和国家基本政策违背那么可以说希望渺茫，比如在减少煤炭产量的时候购买煤矿的采矿权，经营煤矿那么会非常惨烈，和前段时间 K12 教育的现象一样。

在公司内部也是一样，如果公司的发展形势是全面上云、技术栈转 Java 等战略方向，那么反其道而行自然不太好。

不过形势很难被分析看到，不然人人都是大师了。有一种有说法我比较认可，形势是群体的动机，而群体的动机又是有影响力的人推动的，归根结底是人性和利益的动机。

安逸和方便的生活是整个人类社会的动机，也是科技的基本驱动力，所以搞出一些让事情变得复杂的发明自然不会有人买单。对于公司来说，盈利是其动机，因此所有活动都需要奔着盈利去。对于团队内部，群体的动机往往是领导的 KPI，那么形势也是如此。

形势的作用就像水流和船的关系，水流的方向是宏观形势的推动方向，而风向是微观形势推动的，靠引擎或者人力的推动是主观能动性。

在很多情况下，甚至只有船长具有主观能动性，其他人不过是在船底部的机舱中卖劳力而已。这些人形如我们，看不到水流的方向，也看感受不到风的方向，仅仅知道的是船长的指令。

他们虽然辛苦，但是不用过多地的耗费精神，也感受不到危险，同样也没有决策的压力。如果一个机舱中的船夫跑出来指点船长的工作，甚至舰队领袖的工作，那么大概率的情况是连船夫也没有资格做了。

而对于一名船长来说，观察风向、看清水流、识别礁石等风险才是他的工作，一名和形势对抗的船长某种程度上来说是不合格的。


=== 职业节点就是行业生态位

博弈的平衡和秩序的形成，产生了生态位，每个人都在自己的生态位生存。从某种程度上来说文明社会并没有比生物圈更文明，只不过作为人类在和平的状态下生存环境更好了。

实力、背景和运气的差距是客观存在的，参与到竞争环境中的个体从来没有平等过，在充分的竞争下形成了某种秩序，这种秩序让个体产生了分层，也就形成了生态位。

如果把《湖南农民考察报告》再多读几遍，发现软件工程和行业也存在相似的结构。软件行业的生态慢慢分化出老板、大厂技术经理、大厂程序员、小厂技术经理、小厂程序员等层次。

如果把精力投资在深入技术上可能得结果是在生态位上被刻画的更死，因此有人把精力投资在生态位的变化上。这两种投资需要保持某种微妙的平衡，既不能太务实，也不能完全务虚。

另外，生态位切换的过程有点类似于甲壳类动物需要蜕壳，虽然在蜕壳完成后可以获得竞争力，但在蜕壳期间很危险。

这样的经历往往就是软件工程从业者焦虑的原因。大多数人都会经历从前端到后端，从业务分析师到项目经理，从技术人员到市场人员来回切换。 切换的过程中充满了不安、竞争力丢失等危险。

一位做前端的朋友告诉我他被提拔为了团队的负责人，直接管理后端、测试、产品等人员。但是他高兴不起来，原因是处于一个非常尴尬的生态位。被提拔的原因是因为在人员不稳定的公司里，他是相对工龄比较久的人。作为团队负责人却没有太多后端、产品等其他经验，无论是在当前岗位还是出去找工作都会不利。

从某种程度上来说，职业发展路线就是在不同的生态位上跳跃，每个生态位就是关键的职业节点。从某些节点上升更加平滑，有些节点上升更加陡峭，而一些节点彻底就是死胡同了。

=== 价值的创造者和争夺者

在前面职业发展路径中聊到，职业发展就是生态位的提升，那么避免不了的两个方向就是技术和管理。

我们需要思考，为什么看似什么也不懂的管理者，收益却远比技术人员高呢？就像马云曾坦言，他不需要很聪明，但是他能找到聪明的人。这虽然是谦虚的说法，但是也表明了他无可比拟的优势和能力。

他是一名优秀的管理者，而不必做一名出色的技术人员。 其实对于管理者而言，其特质并不像普世价值说的那样：温良谦虚的君子。而更像是狮子在他的领地管理森林、草原和牛羊。

所以做技术的人和做管理者的人在认知上有两项极大的差异： 做技术的人关注创造价值，而做管理的人往往关注争夺价值。

当然这两项特质可能发生的同一个人身上，也可能某些人两者都不具备。创造价值也可以分为为别人创造价值，也可以解读成为自己创造价值。而争夺价值的人同样可以被理解为为团队争夺价值或者在团队内部为自己争夺价值。

对此种种，我们不便用世俗的道德评价它们。往往我们谈论的政治手段，更多的是争夺价值。

在争夺价值的思维里，才会分析权利的构成、形势、动机和利益问题；而在实施争夺价值行为的过程中，才会利用政治的手段。这些手段可以是具体的心理学攻势、谈判、游说等具体的行为。

心理学的技巧有：群体认同、沉默、肢体暗示、恐吓；谈判技巧有：制衡、制造稀缺；游说的技巧：利害转换。这些内容我们挑一些有趣和有用的重点讨论。

=== 政治的手段：一些心理学

落地政治有写不完的内容，包括一些令人不齿的技巧。由于政治本身就是影响人的技术，从某种程度上来看，也有很多科学性的内容可以使用。

一些心理学的书籍坦诚的就说，某些心理学技巧就是为服务政治而来的。比如 NLP 神经语言程式学（不是自然语言处理的 NLP）就是一种通过心理暗示的方式影响他人的行为和决策。他的理论基础是：人脑是一种通过反馈不断修改和调整自己下一次判断的"程序"，这种程序可以自我学习。比如，打一个人伸出的手背，这个人就会缩回，那么下一次只要发出打手的信号，就会不自觉的缩回，这就是一种神经语言程序的修改。

人类有一些固有的思维程序可以加以利用，也可以通过某种手段修改其他人的思维程序。

举一个小的例子，在历史的场合中，和自己行为相似的人往往是同族，于是大多数人都被印上了一段行为。就是和自己行为相似的人，可以信任。于是利用这一点，我们可以通过可以模仿他人的行为、口头禅、习惯来制造信任。

这一点不用多解释，可以试一试。

==== 群体认同

一个和政治手段挂钩的心理学方法是群体认同，这也是从古至今的经典方法。

所谓政治就是把"把朋友搞得多多的，敌人搞得少少的"，因此需要想清楚目标，"谁是我们的朋友，随时我们的敌人"。 而回答这个问题就需要分析什么是"我们"。

有一个段子是四个人的宿舍可以创建出多少个群？如果不算两个人对话形式，三人以上的群可以创建 5 个。 那么这里的"我们"的数量就是 5。

你说这有什么用呢？我们再看一个例子。

一名女性在生活中遭遇不公，可能会有两种抱怨的方式。抱怨性别矛盾：男人都不是好东西；抱怨阶级矛盾：有钱人都不是好东西。

历史上鸦片战争时，一名老百姓也可能会有两种抱怨的方式。抱怨清政府：满人都不是好东西；抱怨国际矛盾：洋人都不是好东西。

我们再补充一个贴近软件行业工作的例子。如果一名程序员受到压迫，被产品经理分配过多的工作量。他会认为这是技术和产品之间的矛盾，抱怨：产品都不是好东西；也可能意识到产品领导和自己的技术领导串通了，抱怨：领导都不是好东西。

"我们" 的概念是人为塑造的，这个过程叫做群体认同。群体认同可以掩盖一些矛盾，这些矛盾可以被掩盖，同样也可以拿出来操作，这便是人类社会最最微妙的部分。在鬼谷子一书中，矛盾被称为"间隙"，纵横家的学说便是建立在"间隙"之上的。

利用群体认同可以转移矛盾，有时候非常有效，也是企业破除部门墙的方法之一。如果一个现代化科技企业，按照技术部门、产品部门、业务部门进行了划分，那么部门墙的出现是早晚的，于是技术部门、产品部门、业务部门各自为政架空 CEO 等企业高层。

除了前面说到的使用外部咨询的方式来解决这些问题外，还有一种方式，即通过启动项目制来解决这些问题。

职能部门和项目团队之间构成了矩阵型的组织体系。在这类矩阵型企业的环境中，身处某个项目中员工会出现两个群体认同。他们既有行政部门的身份认同，也有项目成员的身份认同，对于高层来说影响和操作的空间就变得更大。

当然一定程度上也会带来行政管理上的浪费，增加管理成本。当总之来说，通过项目的群体认同，转移跨部门之间的矛盾往往是有效的。

注意这里说的是转移矛盾，而不是消灭。在矛盾论中，矛盾无法被消灭，只能转移，一个大的矛盾消失了，另外一个矛盾就会出现，矛盾是推动事物发展的基本规律，我们只能识别出不能容忍的主要矛盾并将其转化到能容忍的矛盾上。

群体认同的另外一种形式是制胜联盟。这种模式在马基雅维利的《君主论》、《独裁者指南》两本书中都有提到。

一个人想要影响或者控制群体，首先需要通过影响一小部分人，并通过这一小部分人来影响和控制群体，这一小部分人叫做制胜联盟。

制胜联盟的影子在公司、国家和团体中随处可见。公司会通过选择忠诚和利益一致的人来作为核心高层（Core Team），影响和控制整个公司；即使简单的学校班级也会建立一个班委。制胜联盟表达的含义是，总有"我们"比其他"我们"更我们一些。

为什么会这样？通过全民投票不行吗？事实证明，群体决策是盲目的，信息无法很快的在整个群体中传播，另外更重要的是制胜联盟的目的是它成为整个系统的凝结核，并且让其它个体尽量保持个体状态，这样的系统才最稳定。 而最不稳定的系统是系统中充满了各种各样势均力敌的凝结核，这些凝结核会相互对立并导致系统撕裂。

一个系统越大，制胜联盟的必要性就越强，而所谓的民主就越不重要。制胜联盟是群体认同中最有价值的地方。如果要引领一个群体，就需要建立凝结核，合并或者消除其他凝结核。如果想要在一个稳定系统种舒服的生存下去，最好的方法也是想尽办法加入这个凝结核。而加入凝结核的方法是保持忠诚或者制造对等的影响力并值得被最大的凝结核吸收。

=== 政治的手段：博弈和谈判

政治手段除了通过心理学造成对他人的影响外，还有一个非常重要的内容，就是谈判。 谈判无处不在，有时候甚至不知道存在的情况下就发生了。在软件行业，软件工程师需要谈需求，谈方案。对于所有的人都需要谈薪资，所以掌握谈判能力的人，更具有优势。

最常见的一种谈判能力就是购物时讲价。有一些人天生就能讲价，将其谈判的能力发挥到极致。通过讲价引出的第一个认知变化就是：不要给可能设限，任何场合都有谈判的空间。当一些事情看似已成定局，或者想改变显得不可能，实际上在条件成熟时都有可能变化。

我在工作以前，以为连锁酒店的价格基本无法修改的，越是正规的酒店越没有谈判的空间。工作后，满世界飞，认知被颠覆。 18 年夏天，公司在西安组织了一次国际培训，我有幸是培训师之一。周末带其它讲师到成都旅行，到达成都后还是下午，因为没有提前定酒店，于是在街上挑选合适的酒店。

我们看到一个非常不错的花园酒店，挂牌价格为最低 800 一间。我进去打了个招呼，问了下价格，被告知价格无法修改，于是灰溜溜的出来了。在出来的一刻，同事进来找我，让酒店接待的服务员看到我们十来个人，于是马上提出，可以帮我办理一个会员卡，而会员卡的价格是 300。 我被震惊了，挂牌价格和真实价格的落差如此之大，我继续询问是否包含早餐，被告知这个价格已经无法包含早餐了。经过大家七嘴八舌的抱怨后，可能是这家酒店属于淡季，最终依然满足了我们的条件。

这次讲价的经历给一个重要的启示：**任何场合都具有谈判的空间。**。博弈论是系统性被用到了商业谈判中，它有各种各样的分类方法。博弈，是社会中每一个人都需要掌握的能力，甚至比做具体的工作更重要，这里有几种博弈的分类，可以作为处理博弈问题时作为参考。

*合作博弈和非合作博弈* 合作博弈是指在这次博弈中能达成共赢的局面，而非合作博弈为很难达成共赢。那么，这两种场景中，需要采用不同的策略达成自己的目标。

如果能基于共赢的情况进行博弈，就可以互相摊牌，让对方看到所有信息，优先让对方达成条件，这样对方会驱动一起达成己方的条件。合作博弈 + 信息透明是最完美的合作状态，但是大多数情况下都不能达到。

如果不能做到合作博弈，博弈就变成了非合作博弈。后者在生活中更为普遍，更残酷。非合作博弈中，参与的各方都希望能达到利益的最大化，于是各方尽可能的隐藏自己的信息，了解对手的信息。

*完全信息/不完全信息博弈* 完全信息/不完全信息博弈是根据信息暴露状态来看的。当我们陷入不同的场景中，就可以利用信息状态的转换来实现博弈目标。

在合作博弈中，转换为完全信息博弈可以对双方更有利；在非合作博弈中，转换为不完全信息博弈，并且尽可能的少暴露自己的信息，了解对方的信息，成功的几率更大。

对任意一方来说信息状态有下面几种：

. 己方不了解对方的信息，己方也不了解己方的信息。
. 己方了解对方信息，己方不了解己方信息。
. 己方不了解对方信息，己方了解己方信息。
. 己方了解对方信息，己方了解己方信息。

如果再组合一下，己方是否了解对方的信息状态，又会有三种情况：

. 对方不了解己方的信息，对方也不了解对方的信息。
. 对方了解对方信息，对方不了解己方信息。
. 对方不了解对方信息，对方了解己方信息。
. 对方了解对方信息，对方了解己方信息。

所以，最优的状态是：

* 己方了解对方信息，己方了解己方信息。对方不了解己方的信息，对方也不了解对方的信息。

最差的状态是：

* 己方不了解对方的信息，己方也不了解己方的信息。对方了解对方信息，对方了解己方信息。

*多阶段博弈* 人和人之间如果只是一次交易，互相欺骗的可能性高，但是如果是持续合作，彼此更倾向于不欺骗对方。这种情况被叫做重复博弈或者又叫多阶段博弈。

认识到重复和单次博弈的区别，对我们谈判用处非常大。举个例子，旅游时用餐和在家门口用餐的博弈场景完全不同。景区的餐厅做的都是一次性生意，欺骗性极强。这种博弈在一次交易完成后一般就没有下次了，就应该尽可能保证当次的利益。

如果是商务合作中，长期合作的合作伙伴，在初期合作时，可以采取让利的策略，先建立合作关系，再从后续的交易中获得价值。

*多方博弈* 多方博弈是指在博弈中，参与方有多个，这样就会产生大量的博弈关系。最经典例子是国际社会中三方会谈，往往有六向双边关系将一个问题变得极其复杂。 当数量超过三时，会变得更加复杂。多方博弈时就需要达成几个目标才能取得较好的效果：

- 获取足够多的支持，制造合作博弈
- 尽量减少非合作博弈
- 找到主要矛盾，将资源投入到核心问题的解决上

=== 总结：政治的真相

政治是说谎的艺术。

真正的政治是暴力和欺骗的艺术，当然在职业环境中，大多数情况下暴力可以替换为职权力，而获取权利的过程也充满了欺骗和伪装。

正是因为政治背后具有欺骗和各种手段，这正是让人们羞于启齿的原因。但是这些欺骗无时不刻出现在生活和工作场合中，甚至让人们产生羞耻也是欺骗的一部分。

这些欺骗是为了更好的实现具体的政治手段，从而建立需要的秩序。这种欺骗从人类奴隶时代就开始了，甚至在人类文明出现之前就开始了。

蜥蜴和章鱼通过调整自身的颜色来伪装自己，从而躲过天敌和捕获猎物；某些蛾类通过伪装翅膀为枯叶和环境融为一起，这些都可以算作欺骗。

原始部落的首领和萨满通过假装和神灵沟通，从而欺骗部落成员，取得统治地位；封建君主欺骗民众，自诩为天子，虚构一套神话体系，让人觉得自己天生优越；西方教皇虚构了上帝，通过宗教进行欺骗。

在普世价值观下，欺骗是全方位的。中国古代儒家教育体系将虚假的价值观从小就植入到普通人的意识中。人性本善，是一种欺骗，掩盖人性自私的原本面目；将君子包装成大公无私的形象，实际上是获取私利的方法；宣传的人人平等也是一种欺骗，客观上个体之间永远不可能平等，贵族阶层一定会比普通人获得更多的资源。

甚至羞耻也是一种谎言。想想一种场景，在古代的丛林中，有一个部落。这个部落有一天打猎获取到了一只肥美的麋鹿，部落的人自然都想分享到麋鹿的美味。为了相对公平，部落首领在没有想好如何分配的情况下，先将麋鹿保存在部落公共的房子里。那么，每一个靠近屋子想打麋鹿主意的人，都会面临其他人的指责。羞愧，其实就是来源于众人的指责，有时候这里的"众人"甚至来自于父母或者家人。

想象上面的场景，如果将麋鹿换成部落中最漂亮的女性会发生什么？每一个靠近漂亮女性的男性都会来自其他男性的攻击、指责，这就是性羞耻的起源。

政治的无耻就在于这里，普世价值的真、善、美只是让对方相信，从而轻易卸下对方的武装。从某种程度上来说，人类发达的大脑不仅能在捕猎的时候做出完美的假动作实现智力对体力的降维打击，也能在人类内部竞争中充分发挥作用。

如果不能理解谎言在政治中的作用，那么从生活中可以随时观察他人，从他说话的动机出发，尝试理解话语背后的动机和目的。

说谎已经被刻画到人类的本性中，普世价值却鼓励别人诚实一点。如果大家都是诚实的，那么女性还需要化妆打扮、男性还需要好面子吗？我们有一天也快忘记，面子的本质也是欺骗——通过穿戴或其他物品伪装自己的经济水平而已。
